services:
  app:
    container_name: abobonjr_app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/go/src/app
    env_file:
      - .env
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DB_CONTAINER_NAME: abobonjr_db
      TZ: Asia/Tokyo
    depends_on:
      db:
        condition: service_healthy
    tty: true

  db:
    container_name: abobonjr_db
    platform: linux/x86_64
    build:
      context: ./
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
