services:
  app:
    container_name: abobonjr_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/go/src/app
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DB_CONTAINER_NAME: abobonjr_db
      TZ: Asia/Tokyo
    depends_on:
      db:
        condition: service_healthy
    tty: true

  db:
    container_name: abobonjr_db
    platform: linux/x86_64
    image: mysql:8.0.29
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/migrations:/docker-entrypoint-initdb.d
