# .air.toml
[build]
cmd = "go build -o ./tmp/main ."
bin = "tmp/main"
full_bin = "APP_ENV=development ./tmp/main"

[watch]
# Multiple directories can be specified as follows:
# dirs = ["dir1", "dir2"]
dirs = ["."]
# Exclude file or directory by pattern
exclude_dir = ["assets", "tmp", "vendor"]
exclude_file = ["go.sum", "go.mod"]
# Filter file types
include_ext = ["go", "tpl", "tmpl", "html"]
# Watch these filename, if they changed, main process will be restart.
include_file = []
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms

[log]
# Show log time
time = false

[color]
# Customize each part's color. If no color is found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete binary after Air ends
clean = true
