linters-settings:
  structcheck:
    type-check: 
      disabled: true
    unused-fields: true
  govet:
    check-shadowing: false
  gocyclo:
    min-complexity: 30
  gocognit:
    min-complexity: 40
  errcheck:
    ignore: ''

issues:
  exclude-files:
    - .*_test\.go
  max-issues-per-linter: 1000
  max-same-issues: 1000

run:
  timeout: 20m
  go: '1.22'

linters:
  disable-all: true
  enable:
    - goimports
    - unused
    - errcheck
    - gocognit
    - gofmt
    - govet
    - misspell
    - staticcheck
    - whitespace
    - gosec
